import Link from "next/link";
import { ProgressBar } from "@/components/ProgressBar";
import { achievements, pets, player } from "@/data/demo";

export default async function PlayerPage({ params }: { params: Promise<{ username: string }> }) {
  const { username } = await params;
  const name = decodeURIComponent(username).replace(/[^a-zA-Z0-9_.-]/g, "").slice(0, 32) || "Player";
  return <section className="profile-page profile-page-v2"><div className="container narrow-wide"><Link href="/leaderboard" className="text-link">← GLOBAL LEADERBOARD</Link><div className="profile-hero profile-hero-v2"><div className="profile-avatar"><div className="profile-aura"/><img src={`https://mc-heads.net/body/${encodeURIComponent(name)}/220`} alt={`${name} Minecraft skin`}/></div><div><span className="eyebrow">PUBLIC CHARACTER PROFILE</span><h1>{name}</h1><div className="profile-badges"><b>{player.rank}</b><b>{player.className}</b><b>SEASON #{player.seasonRank}</b></div><p>Public profile menampilkan progression kompetitif dan collection yang memang dipilih untuk terlihat. Data sensitif/account tools tetap hanya ada di Command Center.</p><div className="profile-power"><span>COMBAT POWER</span><b>{player.power.toLocaleString()}</b></div></div></div><div className="profile-stats">{[['Level',String(player.level)],['Coins',player.coins.toLocaleString()],['Playtime',player.playtime],['Kills',player.kills.toLocaleString()],['Deaths',player.deaths.toLocaleString()],['Guild',player.guild]].map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div><div className="profile-columns"><div className="skill-panel"><h2>CORE SKILLS</h2>{player.skills.map(s=><div className="skill-row" key={s.name}><span>{s.name}</span><div><i style={{width:`${s.progress}%`}}/></div><b>Lv. {s.level}</b></div>)}</div><div className="skill-panel"><h2>SHOWCASE COLLECTION</h2><div className="profile-pets">{pets.filter(p=>p.owned).map(p=><div key={p.name}><i>{p.icon}</i><span><b>{p.name}</b><small>{p.rarity} · LV {p.level}</small></span></div>)}</div></div></div><div className="skill-panel"><h2>ACHIEVEMENT SHOWCASE</h2><div className="profile-achievements">{achievements.slice(0,3).map(a=><div key={a.name}><span>{a.done?'✓':'◌'}</span><div><b>{a.name}</b><small>{a.reward}</small></div><ProgressBar value={a.progress} max={a.total}/></div>)}</div></div></div></section>;
}
